title: Programming Design Systems
baseurl: ""
permalink: /:title/
exclude: [Gemfile, Gemfile.lock]
imageproxy_url: http://assets.runemadsen.com/600x
gems:
  - jekyll-assets
assets:
  compress:
    css: true
    js: true
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
